### ISSUE TITLE
Compare 'require to publish' modules

### ISSUE THREAD

**Issue by jodyHamilton** [zivtech/bear#130]
When forms are long, required fields are a problem because they make it impossible for a user to save their data until they complete all required fields. We often have use cases when we want the user to be able to save an unpublished incomplete node form, and then later when publishing it have the validation happen to ensure all required fields are complete.

I found some D7 modules that allow this. Please try each one in a separate bear 7 PR and configure so we can compare and see which works best. 

'Save draft' module supposedly contains this feature: https://www.drupal.org/node/1786442

This module seems possibly most promising: https://github.com/chapter-three/require-to-publish

And this one sounds similar: https://www.drupal.org/sandbox/abhishek_pareek/2549931

**Comment by dzink** [comment]
> 'Save draft' module supposedly contains this feature: https://www.drupal.org/node/1786442
- this patch doesn't apply to 7.1-1.4 or 7.1-1.x-dev. Also the comments say it doesn't really work after the first validation.
  PR: https://github.com/zivtech/bear/pull/131

> This module seems possibly most promising: https://github.com/chapter-three/require-to-publish
- Works out of the box with an intuitive interface. Nice interactivity too.

PR: https://github.com/zivtech/bear/pull/133
https://87f21630-9d09-45e8-9c7f-1e64ae988f2d.probo.build/

> And this one sounds similar: https://www.drupal.org/sandbox/abhishek_pareek/2549931
- Seems like this one is missing something, ie a "Save Draft" button. I added the save_draft module and it works, except: 
  1) there isn't any ui indicating that the field is required on draft
  2) instead of making the setting for a field a radio box like the chapter 3 module does, the field is two checkboxes, so technically you could choose both "Required field" and "Required validation only when publishing" if you wanted to, which makes no sense.
  3) the field becomes unavailable in the structure > content types > basic page > manage fields menu 

https://github.com/zivtech/bear/pull/134
https://755bbde7-5a15-41aa-8de6-ad8aa4d53746.probo.build/
